{% set version = "3.7.0" %}
{% set commit = "fb45473ac27833154724bac04136c601e7b2a6f0" %}

package:
  name: 'r-misha'
  version: '{{ version }}'

source:
  url: 'https://github.com/tanaylab/misha/archive/{{ commit }}.zip'
  sha256: 304d33bb514e3532cedbf451e189d5367cc80bdce86462b4426f8f3cc4809391

build:
  # https://github.com/tanaylab/misha/issues/9
  skip: True  # [osx]
  number: 0
  rpaths:
    - lib/R/lib
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - r-base
    - r-devtools
  run:
    - r-base

test:
  commands:
    - '$R -e "library(misha)"'

about:
  home: 'https://tanaylab.github.io/misha/index.html'
  license: GPL-2
  summary: 'Toolkit for analysis of genomic data'

extra:
  maintainers:
    - Misha Hoichman <misha@hoichman.com>
